version: "3.7"

networks:
  network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24
         gateway: 172.20.0.1

services:
  web:
    image: szalbuque/cadastro-app-php:1.0
    ports:
      - "8081:80"
    networks:
      network:
        ipv4_address: 172.17.0.3
    

  db:
    image: szalbuque/cadastro-db
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: "cadastro"
    ports:
      - "3307:3306"
    networks:
      network:
        ipv4_address: 172.17.0.2
   